### ISSUE TITLE
Windows console.log() not working

### ISSUE THREAD

**Issue by elburz** [openhybrid/object#20]
I checked server.js and the debug is set to true, but even then I'm not seeing any console.log() messages I added to the obj.object.on() function in the sensorAndSlider example. Anything else I'd need to do to get the console.log() working?

Windows 7
Node 0.12.9

**Comment by vheun** [comment]
The obj.object.on() is called in the Reality Editor. It is a separate software then the object server.
This is why you do not see console.log() messages.

You will need to load the debug interface for your iOS device.
